### ISSUE TITLE
Test for whitespace cleanliness

### ISSUE THREAD

**Issue by straitm** [mastbaum/cog#3]
I would like a test that checks whether the branch:

* introduces new TAB characters.  I think it would be sufficient to test whether any changed lines contain new TABs, even though this would have some false positives.

* introduces new files without EOF newlines, or deletes the EOF newline from existing files.

And possibly, although these may be controversial:

* changes lines only by adding whitespace at the end.

* Introduces new lines with trailing whitespace

* adds extra newlines to the end of a file or creates a new file with more than one trailing newline.

And possibly, although maybe unlikely to ever happen:

* introduces DOS-style line breaks (i.e. CRLF)

* introduces other bad ASCII characters, meaning, I think, 0x00-0x09, 0x0b-0x1f, and 0x7f

Which raises the question of whether non-ASCII is allowed.  We already have quite a few files using UTF-8 dashes, e.g. ChanSWStatusHist.cc.  Is this ok with us?  If not, we should test for it, since it's quite difficult to tell them apart at a glance.

**Comment by mastbaum** [comment]
closed by #7
